![ngo_project_image](ngo_project_image.jpg)

GoodThought NGO has been a catalyst for positive change, focusing its efforts on education, healthcare, and sustainable development to make a significant difference in communities worldwide. With this mission, GoodThought has orchestrated an array of assignments aimed at uplifting underprivileged populations and fostering long-term growth.

This project offers a hands-on opportunity to explore how data-driven insights can direct and enhance these humanitarian efforts. In this project, you'll engage with the GoodThought PostgreSQL database, which encapsulates detailed records of assignments, funding, impacts, and donor activities from 2010 to 2023. This comprehensive dataset includes:

- **`Assignments`:** Details about each project, including its name, duration (start and end dates), budget, geographical region, and the impact score.
- **`Donations`:** Records of financial contributions, linked to specific donors and assignments, highlighting how financial support is allocated and utilized.
- **`Donors`:** Information on individuals and organizations that fund GoodThought’s projects, including donor types.

Refer to the below ERD diagram for a visual representation of the relationships between these data tables:

![ERD](ERD.png)


You will execute SQL queries to answer two questions, as listed in the instructions. Good luck!

In [4]:
-- highest_donation_assignments
SELECT 
	assignment_name, 
	region, 
	donor_type, 
	ROUND(SUM(amount),2) AS rounded_total_donation_amount 
FROM
	public.donations 
	JOIN public.assignments a ON public.donations.assignment_id = a.assignment_id 
	JOIN public.donors ON public.donations.donor_id = public.donors.donor_id 
GROUP BY assignment_name, region, donor_type 
ORDER BY 4 DESC
LIMIT 5;

   assignment_name region    donor_type  rounded_total_donation_amount
0  Assignment_3033   East    Individual                        3840.66
1   Assignment_300   West  Organization                        3133.98
2  Assignment_4114  North  Organization                        2778.57
3  Assignment_1765   West  Organization                        2626.98
4   Assignment_268   East    Individual                        2488.69

In [5]:
-- top_regional_impact_assignments
WITH regional_ranks AS (
	SELECT 
		a.assignment_name, 
		a.region,
		a.impact_score,
		COUNT(d.donation_id) AS num_total_donations,
		ROW_NUMBER() OVER(PARTITION BY a.region ORDER BY a.impact_score DESC) AS rank_num 
	FROM assignments a
		JOIN donations d
		ON a.assignment_id = d.assignment_id 
	GROUP BY 1,2,3
)

SELECT 
	assignment_name, 
	region,
	impact_score,
	num_total_donations	
FROM regional_ranks
WHERE rank_num = 1
ORDER BY region;

   assignment_name region  impact_score  num_total_donations
0   Assignment_316   East         10.00                    2
1  Assignment_2253  North          9.99                    1
2  Assignment_3547  South         10.00                    1
3  Assignment_2794   West          9.99                    2